name: swaggerparserissuerepro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  swagger_parser: ^1.14.1
  freezed: ^2.4.5
  retrofit_generator: ^8.0.5
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true